/**
 * Build the RecoveryTipsEmail to a TypeScript constant file
 * Run with: bun packages/email/emails/recovery-tips/build-template.ts
 */

import { render } from "@react-email/components";
import { writeFileSync } from "fs";
import { join } from "path";
import RecoveryTipsEmail from "../recovery-tips";

async function main() {
  // Render with placeholder values
  const html = await render(
    RecoveryTipsEmail({
      recipientName: "{{RECIPIENT_NAME}}",
      unsubscribeUrl: "{{UNSUBSCRIBE_URL}}",
    }),
  );

  // Escape backticks and $ for template literal
  const escapedHtml = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(
    /\$/g,
    "\\$",
  );

  // Generate TypeScript file with the template
  const tsContent =
    `// Auto-generated by: bun packages/email/emails/recovery-tips/build-template.ts
// Do not edit manually - edit packages/email/emails/recovery-tips.tsx instead

export const RECOVERY_TIPS_EMAIL_TEMPLATE = \`${escapedHtml}\`;

export function renderRecoveryTipsEmail(data: {
    recipientName?: string;
    unsubscribeUrl?: string;
}): string {
    return RECOVERY_TIPS_EMAIL_TEMPLATE
        .replace(/\\{\\{RECIPIENT_NAME\\}\\}/g, data.recipientName || "there")
        .replace(/\\{\\{UNSUBSCRIBE_URL\\}\\}/g, data.unsubscribeUrl || "https://thetismedical.com/unsubscribe");
}
`;

  // Output path - write to the Edge Function directory
  const outputPath = join(
    __dirname,
    "../../../../services/thetis/supabase/functions/send-recovery-email/email-template.ts",
  );

  writeFileSync(outputPath, tsContent, "utf-8");
  console.log(`✅ Template written to: ${outputPath}`);
  console.log("\nPlaceholders in template:");
  console.log("- {{RECIPIENT_NAME}}");
  console.log("- {{UNSUBSCRIBE_URL}}");
}

main();
