/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandardIndexRouteImport } from './routes/standard/index'
import { Route as PremiumIndexRouteImport } from './routes/premium/index'
import { Route as PlantarFasciitisIndexRouteImport } from './routes/plantar-fasciitis/index'
import { Route as StandardCertificateRouteImport } from './routes/standard/certificate'
import { Route as StandardSlugRouteImport } from './routes/standard/$slug'
import { Route as PlantarFasciitisSlugRouteImport } from './routes/plantar-fasciitis/$slug'

const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardIndexRoute = StandardIndexRouteImport.update({
  id: '/standard/',
  path: '/standard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumIndexRoute = PremiumIndexRouteImport.update({
  id: '/premium/',
  path: '/premium/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantarFasciitisIndexRoute = PlantarFasciitisIndexRouteImport.update({
  id: '/plantar-fasciitis/',
  path: '/plantar-fasciitis/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardCertificateRoute = StandardCertificateRouteImport.update({
  id: '/standard/certificate',
  path: '/standard/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardSlugRoute = StandardSlugRouteImport.update({
  id: '/standard/$slug',
  path: '/standard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantarFasciitisSlugRoute = PlantarFasciitisSlugRouteImport.update({
  id: '/plantar-fasciitis/$slug',
  path: '/plantar-fasciitis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/plantar-fasciitis/$slug': typeof PlantarFasciitisSlugRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/standard/certificate': typeof StandardCertificateRoute
  '/plantar-fasciitis/': typeof PlantarFasciitisIndexRoute
  '/premium/': typeof PremiumIndexRoute
  '/standard/': typeof StandardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/plantar-fasciitis/$slug': typeof PlantarFasciitisSlugRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/standard/certificate': typeof StandardCertificateRoute
  '/plantar-fasciitis': typeof PlantarFasciitisIndexRoute
  '/premium': typeof PremiumIndexRoute
  '/standard': typeof StandardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/plantar-fasciitis/$slug': typeof PlantarFasciitisSlugRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/standard/certificate': typeof StandardCertificateRoute
  '/plantar-fasciitis/': typeof PlantarFasciitisIndexRoute
  '/premium/': typeof PremiumIndexRoute
  '/standard/': typeof StandardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/plantar-fasciitis/$slug'
    | '/standard/$slug'
    | '/standard/certificate'
    | '/plantar-fasciitis/'
    | '/premium/'
    | '/standard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/plantar-fasciitis/$slug'
    | '/standard/$slug'
    | '/standard/certificate'
    | '/plantar-fasciitis'
    | '/premium'
    | '/standard'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/plantar-fasciitis/$slug'
    | '/standard/$slug'
    | '/standard/certificate'
    | '/plantar-fasciitis/'
    | '/premium/'
    | '/standard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  PlantarFasciitisSlugRoute: typeof PlantarFasciitisSlugRoute
  StandardSlugRoute: typeof StandardSlugRoute
  StandardCertificateRoute: typeof StandardCertificateRoute
  PlantarFasciitisIndexRoute: typeof PlantarFasciitisIndexRoute
  PremiumIndexRoute: typeof PremiumIndexRoute
  StandardIndexRoute: typeof StandardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/': {
      id: '/standard/'
      path: '/standard'
      fullPath: '/standard/'
      preLoaderRoute: typeof StandardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/': {
      id: '/premium/'
      path: '/premium'
      fullPath: '/premium/'
      preLoaderRoute: typeof PremiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantar-fasciitis/': {
      id: '/plantar-fasciitis/'
      path: '/plantar-fasciitis'
      fullPath: '/plantar-fasciitis/'
      preLoaderRoute: typeof PlantarFasciitisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/certificate': {
      id: '/standard/certificate'
      path: '/standard/certificate'
      fullPath: '/standard/certificate'
      preLoaderRoute: typeof StandardCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/$slug': {
      id: '/standard/$slug'
      path: '/standard/$slug'
      fullPath: '/standard/$slug'
      preLoaderRoute: typeof StandardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantar-fasciitis/$slug': {
      id: '/plantar-fasciitis/$slug'
      path: '/plantar-fasciitis/$slug'
      fullPath: '/plantar-fasciitis/$slug'
      preLoaderRoute: typeof PlantarFasciitisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  PlantarFasciitisSlugRoute: PlantarFasciitisSlugRoute,
  StandardSlugRoute: StandardSlugRoute,
  StandardCertificateRoute: StandardCertificateRoute,
  PlantarFasciitisIndexRoute: PlantarFasciitisIndexRoute,
  PremiumIndexRoute: PremiumIndexRoute,
  StandardIndexRoute: StandardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
