/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandardIndexRouteImport } from './routes/standard/index'
import { Route as PremiumIndexRouteImport } from './routes/premium/index'
import { Route as StandardSlugRouteImport } from './routes/standard/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardIndexRoute = StandardIndexRouteImport.update({
  id: '/standard/',
  path: '/standard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumIndexRoute = PremiumIndexRouteImport.update({
  id: '/premium/',
  path: '/premium/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardSlugRoute = StandardSlugRouteImport.update({
  id: '/standard/$slug',
  path: '/standard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/premium': typeof PremiumIndexRoute
  '/standard': typeof StandardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/premium': typeof PremiumIndexRoute
  '/standard': typeof StandardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/standard/$slug': typeof StandardSlugRoute
  '/premium/': typeof PremiumIndexRoute
  '/standard/': typeof StandardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/standard/$slug' | '/premium' | '/standard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/standard/$slug' | '/premium' | '/standard'
  id: '__root__' | '/' | '/standard/$slug' | '/premium/' | '/standard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandardSlugRoute: typeof StandardSlugRoute
  PremiumIndexRoute: typeof PremiumIndexRoute
  StandardIndexRoute: typeof StandardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/': {
      id: '/standard/'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/': {
      id: '/premium/'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/$slug': {
      id: '/standard/$slug'
      path: '/standard/$slug'
      fullPath: '/standard/$slug'
      preLoaderRoute: typeof StandardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandardSlugRoute: StandardSlugRoute,
  PremiumIndexRoute: PremiumIndexRoute,
  StandardIndexRoute: StandardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
