/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandardIndexRouteImport } from './routes/standard/index'
import { Route as ProfessionalsIndexRouteImport } from './routes/professionals/index'
import { Route as PremiumIndexRouteImport } from './routes/premium/index'
import { Route as EssentialsIndexRouteImport } from './routes/essentials/index'
import { Route as StandardWeekWeekDayDayRouteImport } from './routes/standard/week/$week/day/$day'
import { Route as EssentialsWeekWeekDayDayRouteImport } from './routes/essentials/week/$week/day/$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardIndexRoute = StandardIndexRouteImport.update({
  id: '/standard/',
  path: '/standard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsIndexRoute = ProfessionalsIndexRouteImport.update({
  id: '/professionals/',
  path: '/professionals/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumIndexRoute = PremiumIndexRouteImport.update({
  id: '/premium/',
  path: '/premium/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsIndexRoute = EssentialsIndexRouteImport.update({
  id: '/essentials/',
  path: '/essentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardWeekWeekDayDayRoute = StandardWeekWeekDayDayRouteImport.update({
  id: '/standard/week/$week/day/$day',
  path: '/standard/week/$week/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsWeekWeekDayDayRoute =
  EssentialsWeekWeekDayDayRouteImport.update({
    id: '/essentials/week/$week/day/$day',
    path: '/essentials/week/$week/day/$day',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essentials': typeof EssentialsIndexRoute
  '/premium': typeof PremiumIndexRoute
  '/professionals': typeof ProfessionalsIndexRoute
  '/standard': typeof StandardIndexRoute
  '/essentials/week/$week/day/$day': typeof EssentialsWeekWeekDayDayRoute
  '/standard/week/$week/day/$day': typeof StandardWeekWeekDayDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essentials': typeof EssentialsIndexRoute
  '/premium': typeof PremiumIndexRoute
  '/professionals': typeof ProfessionalsIndexRoute
  '/standard': typeof StandardIndexRoute
  '/essentials/week/$week/day/$day': typeof EssentialsWeekWeekDayDayRoute
  '/standard/week/$week/day/$day': typeof StandardWeekWeekDayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essentials/': typeof EssentialsIndexRoute
  '/premium/': typeof PremiumIndexRoute
  '/professionals/': typeof ProfessionalsIndexRoute
  '/standard/': typeof StandardIndexRoute
  '/essentials/week/$week/day/$day': typeof EssentialsWeekWeekDayDayRoute
  '/standard/week/$week/day/$day': typeof StandardWeekWeekDayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/essentials'
    | '/premium'
    | '/professionals'
    | '/standard'
    | '/essentials/week/$week/day/$day'
    | '/standard/week/$week/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/essentials'
    | '/premium'
    | '/professionals'
    | '/standard'
    | '/essentials/week/$week/day/$day'
    | '/standard/week/$week/day/$day'
  id:
    | '__root__'
    | '/'
    | '/essentials/'
    | '/premium/'
    | '/professionals/'
    | '/standard/'
    | '/essentials/week/$week/day/$day'
    | '/standard/week/$week/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssentialsIndexRoute: typeof EssentialsIndexRoute
  PremiumIndexRoute: typeof PremiumIndexRoute
  ProfessionalsIndexRoute: typeof ProfessionalsIndexRoute
  StandardIndexRoute: typeof StandardIndexRoute
  EssentialsWeekWeekDayDayRoute: typeof EssentialsWeekWeekDayDayRoute
  StandardWeekWeekDayDayRoute: typeof StandardWeekWeekDayDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/': {
      id: '/standard/'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/': {
      id: '/professionals/'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/': {
      id: '/premium/'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials/': {
      id: '/essentials/'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof EssentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/week/$week/day/$day': {
      id: '/standard/week/$week/day/$day'
      path: '/standard/week/$week/day/$day'
      fullPath: '/standard/week/$week/day/$day'
      preLoaderRoute: typeof StandardWeekWeekDayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials/week/$week/day/$day': {
      id: '/essentials/week/$week/day/$day'
      path: '/essentials/week/$week/day/$day'
      fullPath: '/essentials/week/$week/day/$day'
      preLoaderRoute: typeof EssentialsWeekWeekDayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssentialsIndexRoute: EssentialsIndexRoute,
  PremiumIndexRoute: PremiumIndexRoute,
  ProfessionalsIndexRoute: ProfessionalsIndexRoute,
  StandardIndexRoute: StandardIndexRoute,
  EssentialsWeekWeekDayDayRoute: EssentialsWeekWeekDayDayRoute,
  StandardWeekWeekDayDayRoute: StandardWeekWeekDayDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
