import {
  Banknote,
  Blend,
  Box,
  BriefcaseBusiness,
  ExternalLink,
  Factory,
  FactoryIcon,
  FileText,
  Pin,
  Printer,
  Recycle,
  ShoppingBag,
  ToyBrick,
  Truck,
} from "lucide-react";

export const jobs = {
  stock: {
    name: "Stock",
    href: "/stock",
    description: "Buy, sell and ship orders.",
    icon: <ShoppingBag />,
    external: false,
    pages: [
      {
        name: "Orders",
        href: "/stock/orders",
        description: "Buy, sell and ship orders.",
        icon: <ShoppingBag />,
        external: false,
      },
      {
        name: "Items",
        href: "/stock/items",
        description: "Keep track of the items we buy and sell.",
        icon: <ToyBrick />,
        external: false,
      },
      {
        name: "Addresses",
        href: "/stock/addresses",
        description: "Manage the Addresses.",
        icon: <FactoryIcon />,
        external: false,
      },
      {
        name: "Companies",
        href: "/stock/companies",
        description: "Manage your Companies.",
        icon: <BriefcaseBusiness />,
        external: false,
      },
      {
        name: "Contacts",
        href: "/stock/contacts",
        description: "Manage your Companies.",
        icon: <BriefcaseBusiness />,
        external: false,
      },
    ],
  },
  finances: {
    name: "Finances",
    href: "/finances",
    description: "Finances.",
    icon: <Banknote />,
    external: false,
    isFeatured: true,
    pages: [
      {
        name: "Settlements",
        href: "/finances/amazon/settlements",
        description: "Payouts from Amazon.",
        icon: <Banknote />,
        external: false,
        isFeatured: true,
      },
      {
        name: "Accounts Instructions",
        href: "/finances/accounts/instructions",
        description: "Instructions for the accounts team.",
        icon: <FileText />,
        external: false,
      },
    ],
  },
  shipping: {
    name: "Shipping",
    href: "/shipping",
    description: "Shipping partners and services.",
    icon: <Truck />,
    external: false,
    pages: [
      {
        name: "UPS",
        href: "https://www.ups.com",
        description: "UPS is a package delivery and shipping company.",
        icon: <Box />,
        external: true,
      },
      {
        name: "P4D",
        href: "https://www.p4d.co.uk/",
        description: "Pallets in the UK to ship parts to MPD.",
        icon: <Truck />,
        external: true,
      },
      {
        name: "Stackery",
        href: "https://stackry.com",
        description: "Stackry unpack and return rejected splints in the US.",
        icon: <Recycle />,
        external: true,
      },
    ],
  },
  suppliers: {
    name: "Suppliers",
    href: "/suppliers",
    description: "Our manufacturing and printing partners.",
    icon: <Factory />,
    external: false,
    pages: [
      {
        name: "MPD",
        href: "https://www.mpd.co.uk/",
        description: "MPD assembles the parts.",
        icon: <Pin />,
        external: true,
      },
      {
        name: "Stretchline",
        href: "https://www.stretchline.com/",
        description: "Stretchline manufactures the elastic with silicone.",
        icon: <Blend />,
        external: true,
      },
      {
        name: "M Wright and Sons",
        href: "https://www.mwright.co.uk/",
        description: "Manufactures webbing.",
        icon: <Factory />,
        external: true,
      },
      {
        name: "Hello Print",
        href: "https://www.helloprint.co.uk/",
        description: "Prints the instructions, business cards and fliers.",
        icon: <Printer />,
        external: true,
      },
    ],
  },
};
