/**
 * Build the CourseAccessEmail to a TypeScript constant file
 * Run with: bun packages/email/emails/course/build-template.ts
 */

import { render } from "@react-email/components";
import { writeFileSync } from "fs";
import { join } from "path";
import CourseAccessEmail from "./course-access";

async function main() {
  // Render with placeholder values
  const html = await render(
    CourseAccessEmail({
      customerEmail: "{{CUSTOMER_EMAIL}}",
      orderNumber: "{{ORDER_NUMBER}}",
      courseType: "{{COURSE_TYPE}}",
      claimUrl: "{{CLAIM_URL}}",
    })
  );

  // Escape backticks and $ for template literal
  const escapedHtml = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  // Generate TypeScript file with the template
  const tsContent = `// Auto-generated by: bun packages/email/emails/course/build-template.ts
// Do not edit manually - edit packages/email/emails/course/course-access.tsx instead

export const COURSE_ACCESS_EMAIL_TEMPLATE = \`${escapedHtml}\`;

export function renderCourseAccessEmail(data: {
    customerEmail: string;
    orderNumber: string;
    courseType: string;
    claimUrl: string;
}): string {
    return COURSE_ACCESS_EMAIL_TEMPLATE
        .replace(/\\{\\{CUSTOMER_EMAIL\\}\\}/g, data.customerEmail)
        .replace(/\\{\\{ORDER_NUMBER\\}\\}/g, data.orderNumber)
        .replace(/\\{\\{COURSE_TYPE\\}\\}/g, data.courseType)
        .replace(/\\{\\{CLAIM_URL\\}\\}/g, data.claimUrl);
}
`;

  // Output path - write to the Edge Function directory
  const outputPath = join(
    __dirname,
    "../../../../services/thetis/supabase/functions/shopify-order-webhook/email-template.ts"
  );

  writeFileSync(outputPath, tsContent, "utf-8");
  console.log(`✅ Template written to: ${outputPath}`);
  console.log("\nPlaceholders in template:");
  console.log("- {{CUSTOMER_EMAIL}}");
  console.log("- {{ORDER_NUMBER}}");
  console.log("- {{COURSE_TYPE}}");
  console.log("- {{CLAIM_URL}}");
}

main();
