/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StockImport } from './routes/stock'
import { Route as FinancesImport } from './routes/finances'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as StockWarehousesImport } from './routes/stock/warehouses'
import { Route as StockSettingsImport } from './routes/stock/settings'
import { Route as StockOrdersImport } from './routes/stock/orders'
import { Route as StockItemsImport } from './routes/stock/items'
import { Route as OrderOrderIdImport } from './routes/order.$orderId'
import { Route as FinancesAmazonIndexImport } from './routes/finances/amazon/index'
import { Route as FinancesAmazonSettlementsIndexImport } from './routes/finances/amazon/settlements/index'
import { Route as FinancesAmazonYearMonthImport } from './routes/finances/amazon/$year.$month'
import { Route as FinancesAmazonSettlementsCountryCodeIndexImport } from './routes/finances/amazon/settlements/$countryCode/index'
import { Route as FinancesAmazonSettlementsCountryCodeReportIdImport } from './routes/finances/amazon/settlements/$countryCode/$reportId'
import { Route as FinancesAmazonSettlementsCountryCodeReportIdXmlImport } from './routes/finances/amazon/settlements/$countryCode/$reportId.xml'

// Create/Update Routes

const StockRoute = StockImport.update({
  path: '/stock',
  getParentRoute: () => rootRoute,
} as any)

const FinancesRoute = FinancesImport.update({
  path: '/finances',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StockWarehousesRoute = StockWarehousesImport.update({
  path: '/warehouses',
  getParentRoute: () => StockRoute,
} as any)

const StockSettingsRoute = StockSettingsImport.update({
  path: '/settings',
  getParentRoute: () => StockRoute,
} as any)

const StockOrdersRoute = StockOrdersImport.update({
  path: '/orders',
  getParentRoute: () => StockRoute,
} as any)

const StockItemsRoute = StockItemsImport.update({
  path: '/items',
  getParentRoute: () => StockRoute,
} as any)

const OrderOrderIdRoute = OrderOrderIdImport.update({
  path: '/order/$orderId',
  getParentRoute: () => rootRoute,
} as any)

const FinancesAmazonIndexRoute = FinancesAmazonIndexImport.update({
  path: '/amazon/',
  getParentRoute: () => FinancesRoute,
} as any)

const FinancesAmazonSettlementsIndexRoute =
  FinancesAmazonSettlementsIndexImport.update({
    path: '/amazon/settlements/',
    getParentRoute: () => FinancesRoute,
  } as any)

const FinancesAmazonYearMonthRoute = FinancesAmazonYearMonthImport.update({
  path: '/amazon/$year/$month',
  getParentRoute: () => FinancesRoute,
} as any)

const FinancesAmazonSettlementsCountryCodeIndexRoute =
  FinancesAmazonSettlementsCountryCodeIndexImport.update({
    path: '/amazon/settlements/$countryCode/',
    getParentRoute: () => FinancesRoute,
  } as any)

const FinancesAmazonSettlementsCountryCodeReportIdRoute =
  FinancesAmazonSettlementsCountryCodeReportIdImport.update({
    path: '/amazon/settlements/$countryCode/$reportId',
    getParentRoute: () => FinancesRoute,
  } as any)

const FinancesAmazonSettlementsCountryCodeReportIdXmlRoute =
  FinancesAmazonSettlementsCountryCodeReportIdXmlImport.update({
    path: '/xml',
    getParentRoute: () => FinancesAmazonSettlementsCountryCodeReportIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesImport
      parentRoute: typeof rootRoute
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockImport
      parentRoute: typeof rootRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdImport
      parentRoute: typeof rootRoute
    }
    '/stock/items': {
      id: '/stock/items'
      path: '/items'
      fullPath: '/stock/items'
      preLoaderRoute: typeof StockItemsImport
      parentRoute: typeof StockImport
    }
    '/stock/orders': {
      id: '/stock/orders'
      path: '/orders'
      fullPath: '/stock/orders'
      preLoaderRoute: typeof StockOrdersImport
      parentRoute: typeof StockImport
    }
    '/stock/settings': {
      id: '/stock/settings'
      path: '/settings'
      fullPath: '/stock/settings'
      preLoaderRoute: typeof StockSettingsImport
      parentRoute: typeof StockImport
    }
    '/stock/warehouses': {
      id: '/stock/warehouses'
      path: '/warehouses'
      fullPath: '/stock/warehouses'
      preLoaderRoute: typeof StockWarehousesImport
      parentRoute: typeof StockImport
    }
    '/finances/amazon/': {
      id: '/finances/amazon/'
      path: '/amazon'
      fullPath: '/finances/amazon'
      preLoaderRoute: typeof FinancesAmazonIndexImport
      parentRoute: typeof FinancesImport
    }
    '/finances/amazon/$year/$month': {
      id: '/finances/amazon/$year/$month'
      path: '/amazon/$year/$month'
      fullPath: '/finances/amazon/$year/$month'
      preLoaderRoute: typeof FinancesAmazonYearMonthImport
      parentRoute: typeof FinancesImport
    }
    '/finances/amazon/settlements/': {
      id: '/finances/amazon/settlements/'
      path: '/amazon/settlements'
      fullPath: '/finances/amazon/settlements'
      preLoaderRoute: typeof FinancesAmazonSettlementsIndexImport
      parentRoute: typeof FinancesImport
    }
    '/finances/amazon/settlements/$countryCode/$reportId': {
      id: '/finances/amazon/settlements/$countryCode/$reportId'
      path: '/amazon/settlements/$countryCode/$reportId'
      fullPath: '/finances/amazon/settlements/$countryCode/$reportId'
      preLoaderRoute: typeof FinancesAmazonSettlementsCountryCodeReportIdImport
      parentRoute: typeof FinancesImport
    }
    '/finances/amazon/settlements/$countryCode/': {
      id: '/finances/amazon/settlements/$countryCode/'
      path: '/amazon/settlements/$countryCode'
      fullPath: '/finances/amazon/settlements/$countryCode'
      preLoaderRoute: typeof FinancesAmazonSettlementsCountryCodeIndexImport
      parentRoute: typeof FinancesImport
    }
    '/finances/amazon/settlements/$countryCode/$reportId/xml': {
      id: '/finances/amazon/settlements/$countryCode/$reportId/xml'
      path: '/xml'
      fullPath: '/finances/amazon/settlements/$countryCode/$reportId/xml'
      preLoaderRoute: typeof FinancesAmazonSettlementsCountryCodeReportIdXmlImport
      parentRoute: typeof FinancesAmazonSettlementsCountryCodeReportIdImport
    }
  }
}

// Create and export the route tree

interface FinancesAmazonSettlementsCountryCodeReportIdRouteChildren {
  FinancesAmazonSettlementsCountryCodeReportIdXmlRoute: typeof FinancesAmazonSettlementsCountryCodeReportIdXmlRoute
}

const FinancesAmazonSettlementsCountryCodeReportIdRouteChildren: FinancesAmazonSettlementsCountryCodeReportIdRouteChildren =
  {
    FinancesAmazonSettlementsCountryCodeReportIdXmlRoute:
      FinancesAmazonSettlementsCountryCodeReportIdXmlRoute,
  }

const FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren =
  FinancesAmazonSettlementsCountryCodeReportIdRoute._addFileChildren(
    FinancesAmazonSettlementsCountryCodeReportIdRouteChildren,
  )

interface FinancesRouteChildren {
  FinancesAmazonIndexRoute: typeof FinancesAmazonIndexRoute
  FinancesAmazonYearMonthRoute: typeof FinancesAmazonYearMonthRoute
  FinancesAmazonSettlementsIndexRoute: typeof FinancesAmazonSettlementsIndexRoute
  FinancesAmazonSettlementsCountryCodeReportIdRoute: typeof FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren
  FinancesAmazonSettlementsCountryCodeIndexRoute: typeof FinancesAmazonSettlementsCountryCodeIndexRoute
}

const FinancesRouteChildren: FinancesRouteChildren = {
  FinancesAmazonIndexRoute: FinancesAmazonIndexRoute,
  FinancesAmazonYearMonthRoute: FinancesAmazonYearMonthRoute,
  FinancesAmazonSettlementsIndexRoute: FinancesAmazonSettlementsIndexRoute,
  FinancesAmazonSettlementsCountryCodeReportIdRoute:
    FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren,
  FinancesAmazonSettlementsCountryCodeIndexRoute:
    FinancesAmazonSettlementsCountryCodeIndexRoute,
}

const FinancesRouteWithChildren = FinancesRoute._addFileChildren(
  FinancesRouteChildren,
)

interface StockRouteChildren {
  StockItemsRoute: typeof StockItemsRoute
  StockOrdersRoute: typeof StockOrdersRoute
  StockSettingsRoute: typeof StockSettingsRoute
  StockWarehousesRoute: typeof StockWarehousesRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockItemsRoute: StockItemsRoute,
  StockOrdersRoute: StockOrdersRoute,
  StockSettingsRoute: StockSettingsRoute,
  StockWarehousesRoute: StockWarehousesRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/finances': typeof FinancesRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/order/$orderId': typeof OrderOrderIdRoute
  '/stock/items': typeof StockItemsRoute
  '/stock/orders': typeof StockOrdersRoute
  '/stock/settings': typeof StockSettingsRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/finances/amazon': typeof FinancesAmazonIndexRoute
  '/finances/amazon/$year/$month': typeof FinancesAmazonYearMonthRoute
  '/finances/amazon/settlements': typeof FinancesAmazonSettlementsIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId': typeof FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren
  '/finances/amazon/settlements/$countryCode': typeof FinancesAmazonSettlementsCountryCodeIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId/xml': typeof FinancesAmazonSettlementsCountryCodeReportIdXmlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/finances': typeof FinancesRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/order/$orderId': typeof OrderOrderIdRoute
  '/stock/items': typeof StockItemsRoute
  '/stock/orders': typeof StockOrdersRoute
  '/stock/settings': typeof StockSettingsRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/finances/amazon': typeof FinancesAmazonIndexRoute
  '/finances/amazon/$year/$month': typeof FinancesAmazonYearMonthRoute
  '/finances/amazon/settlements': typeof FinancesAmazonSettlementsIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId': typeof FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren
  '/finances/amazon/settlements/$countryCode': typeof FinancesAmazonSettlementsCountryCodeIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId/xml': typeof FinancesAmazonSettlementsCountryCodeReportIdXmlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/finances': typeof FinancesRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/order/$orderId': typeof OrderOrderIdRoute
  '/stock/items': typeof StockItemsRoute
  '/stock/orders': typeof StockOrdersRoute
  '/stock/settings': typeof StockSettingsRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/finances/amazon/': typeof FinancesAmazonIndexRoute
  '/finances/amazon/$year/$month': typeof FinancesAmazonYearMonthRoute
  '/finances/amazon/settlements/': typeof FinancesAmazonSettlementsIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId': typeof FinancesAmazonSettlementsCountryCodeReportIdRouteWithChildren
  '/finances/amazon/settlements/$countryCode/': typeof FinancesAmazonSettlementsCountryCodeIndexRoute
  '/finances/amazon/settlements/$countryCode/$reportId/xml': typeof FinancesAmazonSettlementsCountryCodeReportIdXmlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/finances'
    | '/stock'
    | '/order/$orderId'
    | '/stock/items'
    | '/stock/orders'
    | '/stock/settings'
    | '/stock/warehouses'
    | '/finances/amazon'
    | '/finances/amazon/$year/$month'
    | '/finances/amazon/settlements'
    | '/finances/amazon/settlements/$countryCode/$reportId'
    | '/finances/amazon/settlements/$countryCode'
    | '/finances/amazon/settlements/$countryCode/$reportId/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/finances'
    | '/stock'
    | '/order/$orderId'
    | '/stock/items'
    | '/stock/orders'
    | '/stock/settings'
    | '/stock/warehouses'
    | '/finances/amazon'
    | '/finances/amazon/$year/$month'
    | '/finances/amazon/settlements'
    | '/finances/amazon/settlements/$countryCode/$reportId'
    | '/finances/amazon/settlements/$countryCode'
    | '/finances/amazon/settlements/$countryCode/$reportId/xml'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/finances'
    | '/stock'
    | '/order/$orderId'
    | '/stock/items'
    | '/stock/orders'
    | '/stock/settings'
    | '/stock/warehouses'
    | '/finances/amazon/'
    | '/finances/amazon/$year/$month'
    | '/finances/amazon/settlements/'
    | '/finances/amazon/settlements/$countryCode/$reportId'
    | '/finances/amazon/settlements/$countryCode/'
    | '/finances/amazon/settlements/$countryCode/$reportId/xml'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  FinancesRoute: typeof FinancesRouteWithChildren
  StockRoute: typeof StockRouteWithChildren
  OrderOrderIdRoute: typeof OrderOrderIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  FinancesRoute: FinancesRouteWithChildren,
  StockRoute: StockRouteWithChildren,
  OrderOrderIdRoute: OrderOrderIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/finances",
        "/stock",
        "/order/$orderId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/finances": {
      "filePath": "finances.tsx",
      "children": [
        "/finances/amazon/",
        "/finances/amazon/$year/$month",
        "/finances/amazon/settlements/",
        "/finances/amazon/settlements/$countryCode/$reportId",
        "/finances/amazon/settlements/$countryCode/"
      ]
    },
    "/stock": {
      "filePath": "stock.tsx",
      "children": [
        "/stock/items",
        "/stock/orders",
        "/stock/settings",
        "/stock/warehouses"
      ]
    },
    "/order/$orderId": {
      "filePath": "order.$orderId.tsx"
    },
    "/stock/items": {
      "filePath": "stock/items.tsx",
      "parent": "/stock"
    },
    "/stock/orders": {
      "filePath": "stock/orders.tsx",
      "parent": "/stock"
    },
    "/stock/settings": {
      "filePath": "stock/settings.tsx",
      "parent": "/stock"
    },
    "/stock/warehouses": {
      "filePath": "stock/warehouses.tsx",
      "parent": "/stock"
    },
    "/finances/amazon/": {
      "filePath": "finances/amazon/index.tsx",
      "parent": "/finances"
    },
    "/finances/amazon/$year/$month": {
      "filePath": "finances/amazon/$year.$month.tsx",
      "parent": "/finances"
    },
    "/finances/amazon/settlements/": {
      "filePath": "finances/amazon/settlements/index.tsx",
      "parent": "/finances"
    },
    "/finances/amazon/settlements/$countryCode/$reportId": {
      "filePath": "finances/amazon/settlements/$countryCode/$reportId.tsx",
      "parent": "/finances",
      "children": [
        "/finances/amazon/settlements/$countryCode/$reportId/xml"
      ]
    },
    "/finances/amazon/settlements/$countryCode/": {
      "filePath": "finances/amazon/settlements/$countryCode/index.tsx",
      "parent": "/finances"
    },
    "/finances/amazon/settlements/$countryCode/$reportId/xml": {
      "filePath": "finances/amazon/settlements/$countryCode/$reportId.xml.tsx",
      "parent": "/finances/amazon/settlements/$countryCode/$reportId"
    }
  }
}
ROUTE_MANIFEST_END */
