/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocumentsImport } from './routes/documents'
import { Route as AppsImport } from './routes/_apps'
import { Route as IndexImport } from './routes/index'
import { Route as AppsStockImport } from './routes/_apps/stock'
import { Route as AppsFinancesImport } from './routes/_apps/finances'
import { Route as AppsStockIndexImport } from './routes/_apps/stock/index'
import { Route as AppsStockStockImport } from './routes/_apps/stock/stock'
import { Route as AppsStockSettingsImport } from './routes/_apps/stock/settings'
import { Route as AppsStockOrdersImport } from './routes/_apps/stock/orders'
import { Route as AppsStockItemsImport } from './routes/_apps/stock/items'
import { Route as AppsStockDirectoryImport } from './routes/_apps/stock/directory'
import { Route as AppsFinancesAmazonIndexImport } from './routes/_apps/finances/amazon/index'
import { Route as DocumentsOrdersOrderIdStocktakeReportImport } from './routes/documents/orders/$orderId/stocktake-report'
import { Route as DocumentsOrdersOrderIdShippingLabelImport } from './routes/documents/orders/$orderId/shipping-label'
import { Route as DocumentsOrdersOrderIdPurchaseOrderImport } from './routes/documents/orders/$orderId/purchase-order'
import { Route as DocumentsOrdersOrderIdInvoiceImport } from './routes/documents/orders/$orderId/invoice'
import { Route as DocumentsOrdersOrderIdCommercialInvoiceImport } from './routes/documents/orders/$orderId/commercial-invoice'
import { Route as AppsFinancesAccountsInstructionsImport } from './routes/_apps/finances/accounts/instructions'
import { Route as AppsFinancesAmazonSettlementsIndexImport } from './routes/_apps/finances/amazon/settlements/index'
import { Route as AppsFinancesAmazonYearMonthImport } from './routes/_apps/finances/amazon/$year.$month'
import { Route as AppsFinancesAmazonSettlementsRegionIndexImport } from './routes/_apps/finances/amazon/settlements/$region/index'
import { Route as AppsFinancesAmazonSettlementsRegionXmlImport } from './routes/_apps/finances/amazon/settlements/$region/xml'
import { Route as AppsFinancesAmazonSettlementsRegionSummaryImport } from './routes/_apps/finances/amazon/settlements/$region/summary'
import { Route as AppsFinancesAmazonSettlementsRegionReportImport } from './routes/_apps/finances/amazon/settlements/$region/report'

// Create/Update Routes

const DocumentsRoute = DocumentsImport.update({
  path: '/documents',
  getParentRoute: () => rootRoute,
} as any)

const AppsRoute = AppsImport.update({
  id: '/_apps',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppsStockRoute = AppsStockImport.update({
  path: '/stock',
  getParentRoute: () => AppsRoute,
} as any)

const AppsFinancesRoute = AppsFinancesImport.update({
  path: '/finances',
  getParentRoute: () => AppsRoute,
} as any)

const AppsStockIndexRoute = AppsStockIndexImport.update({
  path: '/',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsStockStockRoute = AppsStockStockImport.update({
  path: '/stock',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsStockSettingsRoute = AppsStockSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsStockOrdersRoute = AppsStockOrdersImport.update({
  path: '/orders',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsStockItemsRoute = AppsStockItemsImport.update({
  path: '/items',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsStockDirectoryRoute = AppsStockDirectoryImport.update({
  path: '/directory',
  getParentRoute: () => AppsStockRoute,
} as any)

const AppsFinancesAmazonIndexRoute = AppsFinancesAmazonIndexImport.update({
  path: '/amazon/',
  getParentRoute: () => AppsFinancesRoute,
} as any)

const DocumentsOrdersOrderIdStocktakeReportRoute =
  DocumentsOrdersOrderIdStocktakeReportImport.update({
    path: '/orders/$orderId/stocktake-report',
    getParentRoute: () => DocumentsRoute,
  } as any)

const DocumentsOrdersOrderIdShippingLabelRoute =
  DocumentsOrdersOrderIdShippingLabelImport.update({
    path: '/orders/$orderId/shipping-label',
    getParentRoute: () => DocumentsRoute,
  } as any)

const DocumentsOrdersOrderIdPurchaseOrderRoute =
  DocumentsOrdersOrderIdPurchaseOrderImport.update({
    path: '/orders/$orderId/purchase-order',
    getParentRoute: () => DocumentsRoute,
  } as any)

const DocumentsOrdersOrderIdInvoiceRoute =
  DocumentsOrdersOrderIdInvoiceImport.update({
    path: '/orders/$orderId/invoice',
    getParentRoute: () => DocumentsRoute,
  } as any)

const DocumentsOrdersOrderIdCommercialInvoiceRoute =
  DocumentsOrdersOrderIdCommercialInvoiceImport.update({
    path: '/orders/$orderId/commercial-invoice',
    getParentRoute: () => DocumentsRoute,
  } as any)

const AppsFinancesAccountsInstructionsRoute =
  AppsFinancesAccountsInstructionsImport.update({
    path: '/accounts/instructions',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonSettlementsIndexRoute =
  AppsFinancesAmazonSettlementsIndexImport.update({
    path: '/amazon/settlements/',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonYearMonthRoute =
  AppsFinancesAmazonYearMonthImport.update({
    path: '/amazon/$year/$month',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonSettlementsRegionIndexRoute =
  AppsFinancesAmazonSettlementsRegionIndexImport.update({
    path: '/amazon/settlements/$region/',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonSettlementsRegionXmlRoute =
  AppsFinancesAmazonSettlementsRegionXmlImport.update({
    path: '/amazon/settlements/$region/xml',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonSettlementsRegionSummaryRoute =
  AppsFinancesAmazonSettlementsRegionSummaryImport.update({
    path: '/amazon/settlements/$region/summary',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

const AppsFinancesAmazonSettlementsRegionReportRoute =
  AppsFinancesAmazonSettlementsRegionReportImport.update({
    path: '/amazon/settlements/$region/report',
    getParentRoute: () => AppsFinancesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_apps': {
      id: '/_apps'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppsImport
      parentRoute: typeof rootRoute
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsImport
      parentRoute: typeof rootRoute
    }
    '/_apps/finances': {
      id: '/_apps/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppsFinancesImport
      parentRoute: typeof AppsImport
    }
    '/_apps/stock': {
      id: '/_apps/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppsStockImport
      parentRoute: typeof AppsImport
    }
    '/_apps/stock/directory': {
      id: '/_apps/stock/directory'
      path: '/directory'
      fullPath: '/stock/directory'
      preLoaderRoute: typeof AppsStockDirectoryImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/stock/items': {
      id: '/_apps/stock/items'
      path: '/items'
      fullPath: '/stock/items'
      preLoaderRoute: typeof AppsStockItemsImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/stock/orders': {
      id: '/_apps/stock/orders'
      path: '/orders'
      fullPath: '/stock/orders'
      preLoaderRoute: typeof AppsStockOrdersImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/stock/settings': {
      id: '/_apps/stock/settings'
      path: '/settings'
      fullPath: '/stock/settings'
      preLoaderRoute: typeof AppsStockSettingsImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/stock/stock': {
      id: '/_apps/stock/stock'
      path: '/stock'
      fullPath: '/stock/stock'
      preLoaderRoute: typeof AppsStockStockImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/stock/': {
      id: '/_apps/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppsStockIndexImport
      parentRoute: typeof AppsStockImport
    }
    '/_apps/finances/accounts/instructions': {
      id: '/_apps/finances/accounts/instructions'
      path: '/accounts/instructions'
      fullPath: '/finances/accounts/instructions'
      preLoaderRoute: typeof AppsFinancesAccountsInstructionsImport
      parentRoute: typeof AppsFinancesImport
    }
    '/documents/orders/$orderId/commercial-invoice': {
      id: '/documents/orders/$orderId/commercial-invoice'
      path: '/orders/$orderId/commercial-invoice'
      fullPath: '/documents/orders/$orderId/commercial-invoice'
      preLoaderRoute: typeof DocumentsOrdersOrderIdCommercialInvoiceImport
      parentRoute: typeof DocumentsImport
    }
    '/documents/orders/$orderId/invoice': {
      id: '/documents/orders/$orderId/invoice'
      path: '/orders/$orderId/invoice'
      fullPath: '/documents/orders/$orderId/invoice'
      preLoaderRoute: typeof DocumentsOrdersOrderIdInvoiceImport
      parentRoute: typeof DocumentsImport
    }
    '/documents/orders/$orderId/purchase-order': {
      id: '/documents/orders/$orderId/purchase-order'
      path: '/orders/$orderId/purchase-order'
      fullPath: '/documents/orders/$orderId/purchase-order'
      preLoaderRoute: typeof DocumentsOrdersOrderIdPurchaseOrderImport
      parentRoute: typeof DocumentsImport
    }
    '/documents/orders/$orderId/shipping-label': {
      id: '/documents/orders/$orderId/shipping-label'
      path: '/orders/$orderId/shipping-label'
      fullPath: '/documents/orders/$orderId/shipping-label'
      preLoaderRoute: typeof DocumentsOrdersOrderIdShippingLabelImport
      parentRoute: typeof DocumentsImport
    }
    '/documents/orders/$orderId/stocktake-report': {
      id: '/documents/orders/$orderId/stocktake-report'
      path: '/orders/$orderId/stocktake-report'
      fullPath: '/documents/orders/$orderId/stocktake-report'
      preLoaderRoute: typeof DocumentsOrdersOrderIdStocktakeReportImport
      parentRoute: typeof DocumentsImport
    }
    '/_apps/finances/amazon/': {
      id: '/_apps/finances/amazon/'
      path: '/amazon'
      fullPath: '/finances/amazon'
      preLoaderRoute: typeof AppsFinancesAmazonIndexImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/$year/$month': {
      id: '/_apps/finances/amazon/$year/$month'
      path: '/amazon/$year/$month'
      fullPath: '/finances/amazon/$year/$month'
      preLoaderRoute: typeof AppsFinancesAmazonYearMonthImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/settlements/': {
      id: '/_apps/finances/amazon/settlements/'
      path: '/amazon/settlements'
      fullPath: '/finances/amazon/settlements'
      preLoaderRoute: typeof AppsFinancesAmazonSettlementsIndexImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/settlements/$region/report': {
      id: '/_apps/finances/amazon/settlements/$region/report'
      path: '/amazon/settlements/$region/report'
      fullPath: '/finances/amazon/settlements/$region/report'
      preLoaderRoute: typeof AppsFinancesAmazonSettlementsRegionReportImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/settlements/$region/summary': {
      id: '/_apps/finances/amazon/settlements/$region/summary'
      path: '/amazon/settlements/$region/summary'
      fullPath: '/finances/amazon/settlements/$region/summary'
      preLoaderRoute: typeof AppsFinancesAmazonSettlementsRegionSummaryImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/settlements/$region/xml': {
      id: '/_apps/finances/amazon/settlements/$region/xml'
      path: '/amazon/settlements/$region/xml'
      fullPath: '/finances/amazon/settlements/$region/xml'
      preLoaderRoute: typeof AppsFinancesAmazonSettlementsRegionXmlImport
      parentRoute: typeof AppsFinancesImport
    }
    '/_apps/finances/amazon/settlements/$region/': {
      id: '/_apps/finances/amazon/settlements/$region/'
      path: '/amazon/settlements/$region'
      fullPath: '/finances/amazon/settlements/$region'
      preLoaderRoute: typeof AppsFinancesAmazonSettlementsRegionIndexImport
      parentRoute: typeof AppsFinancesImport
    }
  }
}

// Create and export the route tree

interface AppsFinancesRouteChildren {
  AppsFinancesAccountsInstructionsRoute: typeof AppsFinancesAccountsInstructionsRoute
  AppsFinancesAmazonIndexRoute: typeof AppsFinancesAmazonIndexRoute
  AppsFinancesAmazonYearMonthRoute: typeof AppsFinancesAmazonYearMonthRoute
  AppsFinancesAmazonSettlementsIndexRoute: typeof AppsFinancesAmazonSettlementsIndexRoute
  AppsFinancesAmazonSettlementsRegionReportRoute: typeof AppsFinancesAmazonSettlementsRegionReportRoute
  AppsFinancesAmazonSettlementsRegionSummaryRoute: typeof AppsFinancesAmazonSettlementsRegionSummaryRoute
  AppsFinancesAmazonSettlementsRegionXmlRoute: typeof AppsFinancesAmazonSettlementsRegionXmlRoute
  AppsFinancesAmazonSettlementsRegionIndexRoute: typeof AppsFinancesAmazonSettlementsRegionIndexRoute
}

const AppsFinancesRouteChildren: AppsFinancesRouteChildren = {
  AppsFinancesAccountsInstructionsRoute: AppsFinancesAccountsInstructionsRoute,
  AppsFinancesAmazonIndexRoute: AppsFinancesAmazonIndexRoute,
  AppsFinancesAmazonYearMonthRoute: AppsFinancesAmazonYearMonthRoute,
  AppsFinancesAmazonSettlementsIndexRoute:
    AppsFinancesAmazonSettlementsIndexRoute,
  AppsFinancesAmazonSettlementsRegionReportRoute:
    AppsFinancesAmazonSettlementsRegionReportRoute,
  AppsFinancesAmazonSettlementsRegionSummaryRoute:
    AppsFinancesAmazonSettlementsRegionSummaryRoute,
  AppsFinancesAmazonSettlementsRegionXmlRoute:
    AppsFinancesAmazonSettlementsRegionXmlRoute,
  AppsFinancesAmazonSettlementsRegionIndexRoute:
    AppsFinancesAmazonSettlementsRegionIndexRoute,
}

const AppsFinancesRouteWithChildren = AppsFinancesRoute._addFileChildren(
  AppsFinancesRouteChildren,
)

interface AppsStockRouteChildren {
  AppsStockDirectoryRoute: typeof AppsStockDirectoryRoute
  AppsStockItemsRoute: typeof AppsStockItemsRoute
  AppsStockOrdersRoute: typeof AppsStockOrdersRoute
  AppsStockSettingsRoute: typeof AppsStockSettingsRoute
  AppsStockStockRoute: typeof AppsStockStockRoute
  AppsStockIndexRoute: typeof AppsStockIndexRoute
}

const AppsStockRouteChildren: AppsStockRouteChildren = {
  AppsStockDirectoryRoute: AppsStockDirectoryRoute,
  AppsStockItemsRoute: AppsStockItemsRoute,
  AppsStockOrdersRoute: AppsStockOrdersRoute,
  AppsStockSettingsRoute: AppsStockSettingsRoute,
  AppsStockStockRoute: AppsStockStockRoute,
  AppsStockIndexRoute: AppsStockIndexRoute,
}

const AppsStockRouteWithChildren = AppsStockRoute._addFileChildren(
  AppsStockRouteChildren,
)

interface AppsRouteChildren {
  AppsFinancesRoute: typeof AppsFinancesRouteWithChildren
  AppsStockRoute: typeof AppsStockRouteWithChildren
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsFinancesRoute: AppsFinancesRouteWithChildren,
  AppsStockRoute: AppsStockRouteWithChildren,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface DocumentsRouteChildren {
  DocumentsOrdersOrderIdCommercialInvoiceRoute: typeof DocumentsOrdersOrderIdCommercialInvoiceRoute
  DocumentsOrdersOrderIdInvoiceRoute: typeof DocumentsOrdersOrderIdInvoiceRoute
  DocumentsOrdersOrderIdPurchaseOrderRoute: typeof DocumentsOrdersOrderIdPurchaseOrderRoute
  DocumentsOrdersOrderIdShippingLabelRoute: typeof DocumentsOrdersOrderIdShippingLabelRoute
  DocumentsOrdersOrderIdStocktakeReportRoute: typeof DocumentsOrdersOrderIdStocktakeReportRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsOrdersOrderIdCommercialInvoiceRoute:
    DocumentsOrdersOrderIdCommercialInvoiceRoute,
  DocumentsOrdersOrderIdInvoiceRoute: DocumentsOrdersOrderIdInvoiceRoute,
  DocumentsOrdersOrderIdPurchaseOrderRoute:
    DocumentsOrdersOrderIdPurchaseOrderRoute,
  DocumentsOrdersOrderIdShippingLabelRoute:
    DocumentsOrdersOrderIdShippingLabelRoute,
  DocumentsOrdersOrderIdStocktakeReportRoute:
    DocumentsOrdersOrderIdStocktakeReportRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/finances': typeof AppsFinancesRouteWithChildren
  '/stock': typeof AppsStockRouteWithChildren
  '/stock/directory': typeof AppsStockDirectoryRoute
  '/stock/items': typeof AppsStockItemsRoute
  '/stock/orders': typeof AppsStockOrdersRoute
  '/stock/settings': typeof AppsStockSettingsRoute
  '/stock/stock': typeof AppsStockStockRoute
  '/stock/': typeof AppsStockIndexRoute
  '/finances/accounts/instructions': typeof AppsFinancesAccountsInstructionsRoute
  '/documents/orders/$orderId/commercial-invoice': typeof DocumentsOrdersOrderIdCommercialInvoiceRoute
  '/documents/orders/$orderId/invoice': typeof DocumentsOrdersOrderIdInvoiceRoute
  '/documents/orders/$orderId/purchase-order': typeof DocumentsOrdersOrderIdPurchaseOrderRoute
  '/documents/orders/$orderId/shipping-label': typeof DocumentsOrdersOrderIdShippingLabelRoute
  '/documents/orders/$orderId/stocktake-report': typeof DocumentsOrdersOrderIdStocktakeReportRoute
  '/finances/amazon': typeof AppsFinancesAmazonIndexRoute
  '/finances/amazon/$year/$month': typeof AppsFinancesAmazonYearMonthRoute
  '/finances/amazon/settlements': typeof AppsFinancesAmazonSettlementsIndexRoute
  '/finances/amazon/settlements/$region/report': typeof AppsFinancesAmazonSettlementsRegionReportRoute
  '/finances/amazon/settlements/$region/summary': typeof AppsFinancesAmazonSettlementsRegionSummaryRoute
  '/finances/amazon/settlements/$region/xml': typeof AppsFinancesAmazonSettlementsRegionXmlRoute
  '/finances/amazon/settlements/$region': typeof AppsFinancesAmazonSettlementsRegionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/finances': typeof AppsFinancesRouteWithChildren
  '/stock/directory': typeof AppsStockDirectoryRoute
  '/stock/items': typeof AppsStockItemsRoute
  '/stock/orders': typeof AppsStockOrdersRoute
  '/stock/settings': typeof AppsStockSettingsRoute
  '/stock/stock': typeof AppsStockStockRoute
  '/stock': typeof AppsStockIndexRoute
  '/finances/accounts/instructions': typeof AppsFinancesAccountsInstructionsRoute
  '/documents/orders/$orderId/commercial-invoice': typeof DocumentsOrdersOrderIdCommercialInvoiceRoute
  '/documents/orders/$orderId/invoice': typeof DocumentsOrdersOrderIdInvoiceRoute
  '/documents/orders/$orderId/purchase-order': typeof DocumentsOrdersOrderIdPurchaseOrderRoute
  '/documents/orders/$orderId/shipping-label': typeof DocumentsOrdersOrderIdShippingLabelRoute
  '/documents/orders/$orderId/stocktake-report': typeof DocumentsOrdersOrderIdStocktakeReportRoute
  '/finances/amazon': typeof AppsFinancesAmazonIndexRoute
  '/finances/amazon/$year/$month': typeof AppsFinancesAmazonYearMonthRoute
  '/finances/amazon/settlements': typeof AppsFinancesAmazonSettlementsIndexRoute
  '/finances/amazon/settlements/$region/report': typeof AppsFinancesAmazonSettlementsRegionReportRoute
  '/finances/amazon/settlements/$region/summary': typeof AppsFinancesAmazonSettlementsRegionSummaryRoute
  '/finances/amazon/settlements/$region/xml': typeof AppsFinancesAmazonSettlementsRegionXmlRoute
  '/finances/amazon/settlements/$region': typeof AppsFinancesAmazonSettlementsRegionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_apps': typeof AppsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/_apps/finances': typeof AppsFinancesRouteWithChildren
  '/_apps/stock': typeof AppsStockRouteWithChildren
  '/_apps/stock/directory': typeof AppsStockDirectoryRoute
  '/_apps/stock/items': typeof AppsStockItemsRoute
  '/_apps/stock/orders': typeof AppsStockOrdersRoute
  '/_apps/stock/settings': typeof AppsStockSettingsRoute
  '/_apps/stock/stock': typeof AppsStockStockRoute
  '/_apps/stock/': typeof AppsStockIndexRoute
  '/_apps/finances/accounts/instructions': typeof AppsFinancesAccountsInstructionsRoute
  '/documents/orders/$orderId/commercial-invoice': typeof DocumentsOrdersOrderIdCommercialInvoiceRoute
  '/documents/orders/$orderId/invoice': typeof DocumentsOrdersOrderIdInvoiceRoute
  '/documents/orders/$orderId/purchase-order': typeof DocumentsOrdersOrderIdPurchaseOrderRoute
  '/documents/orders/$orderId/shipping-label': typeof DocumentsOrdersOrderIdShippingLabelRoute
  '/documents/orders/$orderId/stocktake-report': typeof DocumentsOrdersOrderIdStocktakeReportRoute
  '/_apps/finances/amazon/': typeof AppsFinancesAmazonIndexRoute
  '/_apps/finances/amazon/$year/$month': typeof AppsFinancesAmazonYearMonthRoute
  '/_apps/finances/amazon/settlements/': typeof AppsFinancesAmazonSettlementsIndexRoute
  '/_apps/finances/amazon/settlements/$region/report': typeof AppsFinancesAmazonSettlementsRegionReportRoute
  '/_apps/finances/amazon/settlements/$region/summary': typeof AppsFinancesAmazonSettlementsRegionSummaryRoute
  '/_apps/finances/amazon/settlements/$region/xml': typeof AppsFinancesAmazonSettlementsRegionXmlRoute
  '/_apps/finances/amazon/settlements/$region/': typeof AppsFinancesAmazonSettlementsRegionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/documents'
    | '/finances'
    | '/stock'
    | '/stock/directory'
    | '/stock/items'
    | '/stock/orders'
    | '/stock/settings'
    | '/stock/stock'
    | '/stock/'
    | '/finances/accounts/instructions'
    | '/documents/orders/$orderId/commercial-invoice'
    | '/documents/orders/$orderId/invoice'
    | '/documents/orders/$orderId/purchase-order'
    | '/documents/orders/$orderId/shipping-label'
    | '/documents/orders/$orderId/stocktake-report'
    | '/finances/amazon'
    | '/finances/amazon/$year/$month'
    | '/finances/amazon/settlements'
    | '/finances/amazon/settlements/$region/report'
    | '/finances/amazon/settlements/$region/summary'
    | '/finances/amazon/settlements/$region/xml'
    | '/finances/amazon/settlements/$region'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/documents'
    | '/finances'
    | '/stock/directory'
    | '/stock/items'
    | '/stock/orders'
    | '/stock/settings'
    | '/stock/stock'
    | '/stock'
    | '/finances/accounts/instructions'
    | '/documents/orders/$orderId/commercial-invoice'
    | '/documents/orders/$orderId/invoice'
    | '/documents/orders/$orderId/purchase-order'
    | '/documents/orders/$orderId/shipping-label'
    | '/documents/orders/$orderId/stocktake-report'
    | '/finances/amazon'
    | '/finances/amazon/$year/$month'
    | '/finances/amazon/settlements'
    | '/finances/amazon/settlements/$region/report'
    | '/finances/amazon/settlements/$region/summary'
    | '/finances/amazon/settlements/$region/xml'
    | '/finances/amazon/settlements/$region'
  id:
    | '__root__'
    | '/'
    | '/_apps'
    | '/documents'
    | '/_apps/finances'
    | '/_apps/stock'
    | '/_apps/stock/directory'
    | '/_apps/stock/items'
    | '/_apps/stock/orders'
    | '/_apps/stock/settings'
    | '/_apps/stock/stock'
    | '/_apps/stock/'
    | '/_apps/finances/accounts/instructions'
    | '/documents/orders/$orderId/commercial-invoice'
    | '/documents/orders/$orderId/invoice'
    | '/documents/orders/$orderId/purchase-order'
    | '/documents/orders/$orderId/shipping-label'
    | '/documents/orders/$orderId/stocktake-report'
    | '/_apps/finances/amazon/'
    | '/_apps/finances/amazon/$year/$month'
    | '/_apps/finances/amazon/settlements/'
    | '/_apps/finances/amazon/settlements/$region/report'
    | '/_apps/finances/amazon/settlements/$region/summary'
    | '/_apps/finances/amazon/settlements/$region/xml'
    | '/_apps/finances/amazon/settlements/$region/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_apps",
        "/documents"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_apps": {
      "filePath": "_apps.tsx",
      "children": [
        "/_apps/finances",
        "/_apps/stock"
      ]
    },
    "/documents": {
      "filePath": "documents.tsx",
      "children": [
        "/documents/orders/$orderId/commercial-invoice",
        "/documents/orders/$orderId/invoice",
        "/documents/orders/$orderId/purchase-order",
        "/documents/orders/$orderId/shipping-label",
        "/documents/orders/$orderId/stocktake-report"
      ]
    },
    "/_apps/finances": {
      "filePath": "_apps/finances.tsx",
      "parent": "/_apps",
      "children": [
        "/_apps/finances/accounts/instructions",
        "/_apps/finances/amazon/",
        "/_apps/finances/amazon/$year/$month",
        "/_apps/finances/amazon/settlements/",
        "/_apps/finances/amazon/settlements/$region/report",
        "/_apps/finances/amazon/settlements/$region/summary",
        "/_apps/finances/amazon/settlements/$region/xml",
        "/_apps/finances/amazon/settlements/$region/"
      ]
    },
    "/_apps/stock": {
      "filePath": "_apps/stock.tsx",
      "parent": "/_apps",
      "children": [
        "/_apps/stock/directory",
        "/_apps/stock/items",
        "/_apps/stock/orders",
        "/_apps/stock/settings",
        "/_apps/stock/stock",
        "/_apps/stock/"
      ]
    },
    "/_apps/stock/directory": {
      "filePath": "_apps/stock/directory.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/stock/items": {
      "filePath": "_apps/stock/items.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/stock/orders": {
      "filePath": "_apps/stock/orders.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/stock/settings": {
      "filePath": "_apps/stock/settings.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/stock/stock": {
      "filePath": "_apps/stock/stock.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/stock/": {
      "filePath": "_apps/stock/index.tsx",
      "parent": "/_apps/stock"
    },
    "/_apps/finances/accounts/instructions": {
      "filePath": "_apps/finances/accounts/instructions.tsx",
      "parent": "/_apps/finances"
    },
    "/documents/orders/$orderId/commercial-invoice": {
      "filePath": "documents/orders/$orderId/commercial-invoice.tsx",
      "parent": "/documents"
    },
    "/documents/orders/$orderId/invoice": {
      "filePath": "documents/orders/$orderId/invoice.tsx",
      "parent": "/documents"
    },
    "/documents/orders/$orderId/purchase-order": {
      "filePath": "documents/orders/$orderId/purchase-order.tsx",
      "parent": "/documents"
    },
    "/documents/orders/$orderId/shipping-label": {
      "filePath": "documents/orders/$orderId/shipping-label.tsx",
      "parent": "/documents"
    },
    "/documents/orders/$orderId/stocktake-report": {
      "filePath": "documents/orders/$orderId/stocktake-report.tsx",
      "parent": "/documents"
    },
    "/_apps/finances/amazon/": {
      "filePath": "_apps/finances/amazon/index.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/$year/$month": {
      "filePath": "_apps/finances/amazon/$year.$month.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/settlements/": {
      "filePath": "_apps/finances/amazon/settlements/index.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/settlements/$region/report": {
      "filePath": "_apps/finances/amazon/settlements/$region/report.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/settlements/$region/summary": {
      "filePath": "_apps/finances/amazon/settlements/$region/summary.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/settlements/$region/xml": {
      "filePath": "_apps/finances/amazon/settlements/$region/xml.tsx",
      "parent": "/_apps/finances"
    },
    "/_apps/finances/amazon/settlements/$region/": {
      "filePath": "_apps/finances/amazon/settlements/$region/index.tsx",
      "parent": "/_apps/finances"
    }
  }
}
ROUTE_MANIFEST_END */
