CREATE TABLE "public"."amazon_reports"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "report_id" text NOT NULL,
    "storage_path" text NOT NULL
);

CREATE UNIQUE INDEX amazon_reports_pkey ON public.amazon_reports USING btree(id);

CREATE UNIQUE INDEX amazon_reports_report_id_key ON public.amazon_reports USING btree(report_id);

CREATE UNIQUE INDEX amazon_reports_storage_path_key ON public.amazon_reports USING btree(storage_path);

ALTER TABLE "public"."amazon_reports"
    ADD CONSTRAINT "amazon_reports_pkey" PRIMARY KEY USING INDEX "amazon_reports_pkey";

ALTER TABLE "public"."amazon_reports"
    ADD CONSTRAINT "amazon_reports_report_id_key" UNIQUE USING INDEX "amazon_reports_report_id_key";

ALTER TABLE "public"."amazon_reports"
    ADD CONSTRAINT "amazon_reports_storage_path_key" UNIQUE USING INDEX "amazon_reports_storage_path_key";

GRANT DELETE ON TABLE "public"."amazon_reports" TO "anon";

GRANT INSERT ON TABLE "public"."amazon_reports" TO "anon";

GRANT REFERENCES ON TABLE "public"."amazon_reports" TO "anon";

GRANT SELECT ON TABLE "public"."amazon_reports" TO "anon";

GRANT TRIGGER ON TABLE "public"."amazon_reports" TO "anon";

GRANT TRUNCATE ON TABLE "public"."amazon_reports" TO "anon";

GRANT UPDATE ON TABLE "public"."amazon_reports" TO "anon";

GRANT DELETE ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT INSERT ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT REFERENCES ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT SELECT ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT TRIGGER ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT TRUNCATE ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT UPDATE ON TABLE "public"."amazon_reports" TO "authenticated";

GRANT DELETE ON TABLE "public"."amazon_reports" TO "service_role";

GRANT INSERT ON TABLE "public"."amazon_reports" TO "service_role";

GRANT REFERENCES ON TABLE "public"."amazon_reports" TO "service_role";

GRANT SELECT ON TABLE "public"."amazon_reports" TO "service_role";

GRANT TRIGGER ON TABLE "public"."amazon_reports" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."amazon_reports" TO "service_role";

GRANT UPDATE ON TABLE "public"."amazon_reports" TO "service_role";

