import { describe, expect, it } from "vitest";
import { prepareOrderItems } from "./utils";
import { OrderView } from "../../../types";

const items = [
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 1,
        "item_sku": null,
        "quantity": -600,
        "item_name": "Instruction Leaflet",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 2,
        "item_sku": "",
        "quantity": -550,
        "item_name": "Ziplock Bag (Large)",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": "",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 3,
        "item_sku": null,
        "quantity": -238,
        "item_name": "Webbing",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 6,
        "item_sku": null,
        "quantity": -600,
        "item_name": "Flier",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 7,
        "item_sku": null,
        "quantity": -512,
        "item_name": "Elastic",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 8,
        "item_sku": "TM-ATRNS-LL",
        "quantity": 300,
        "item_name": "Night Splint - Large Left (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 9,
        "item_sku": "TM-ATRNS-LR",
        "quantity": 250,
        "item_name": "Night Splint - Large Right (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 16,
        "item_sku": null,
        "quantity": -600,
        "item_name": "Business Card",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 28,
        "item_sku": null,
        "quantity": -250,
        "item_name": "Shell - Right Large",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 29,
        "item_sku": null,
        "quantity": -300,
        "item_name": "Shell - Left Large",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 31,
        "item_sku": null,
        "quantity": -50,
        "item_name": "Shell - Left Small",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 43,
        "item_sku": "TM-ATRNS-SL",
        "quantity": 50,
        "item_name": "Night Splint - Small Left (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 45,
        "item_sku": "",
        "quantity": -50,
        "item_name": "Ziplock Bag (Small)",
        "item_type": "part",
        "item_hs_code": null,
        "item_country_of_origin": "",
    },
    {
        "tax": 0.2,
        "depth": 0,
        "price": 11.69,
        "total": 7715.4,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 13,
        "item_sku": null,
        "quantity": 550,
        "item_name": "Assembly of Large Splint",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0.2,
        "depth": 0,
        "price": 0.71,
        "total": 468.6,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 14,
        "item_sku": null,
        "quantity": 550,
        "item_name": "Packaging of Large Splint in Bag",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0.2,
        "depth": 0,
        "price": 11.27,
        "total": 676.2,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 12,
        "item_sku": null,
        "quantity": 50,
        "item_name": "Assembly of Small Splint",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0.2,
        "depth": 0,
        "price": 0.69,
        "total": 41.4,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 44,
        "item_sku": "",
        "quantity": 50,
        "item_name": "Packaging of Small Splint in Bag",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": "",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 13,
        "item_sku": null,
        "quantity": -550,
        "item_name": "Assembly of Large Splint",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 14,
        "item_sku": null,
        "quantity": -550,
        "item_name": "Packaging of Large Splint in Bag",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 12,
        "item_sku": null,
        "quantity": -50,
        "item_name": "Assembly of Small Splint",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": null,
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 44,
        "item_sku": "",
        "quantity": -50,
        "item_name": "Packaging of Small Splint in Bag",
        "item_type": "service",
        "item_hs_code": null,
        "item_country_of_origin": "",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 9,
        "item_sku": "TM-ATRNS-LR",
        "quantity": 250,
        "item_name": "Night Splint - Large Right (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 8,
        "item_sku": "TM-ATRNS-LL",
        "quantity": 300,
        "item_name": "Night Splint - Large Left (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
    {
        "tax": 0,
        "depth": 0,
        "price": 0,
        "total": 0,
        "width": 0,
        "height": 0,
        "weight": 0,
        "address": {
            "id": 3,
            "city": "Westbury",
            "code": "BA13 4LS",
            "name": "MPD",
            "line_1": "Unit 4 Commerce Business Centre",
            "line_2": "West Wilts Trading Estate",
            "region": "Wiltshire",
            "country": "United Kingdom",
            "is_active": true,
            "company_id": 2,
            "holds_stock": true,
            "is_default_billing": false,
            "is_default_shipping": true,
        },
        "item_id": 43,
        "item_sku": "TM-ATRNS-SL",
        "quantity": 50,
        "item_name": "Night Splint - Small Left (Bag)",
        "item_type": "product",
        "item_hs_code": 902110,
        "item_country_of_origin": "United Kingdom",
    },
];

describe("prepareOrderItems", () => {
    it("should return exactly 3 items", () => {
        // Arrange
        const mockOrder: OrderView = {
            order_type: "purchase",
            items: items,
        };

        // Act
        const result = prepareOrderItems(mockOrder);

        console.log(result);

        // Assert
        expect(result).toHaveLength(6);
    });
});
