-- -- Enable RLS
-- ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE items ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
-- -- Create RLS policies
-- CREATE POLICY "Users can access their company's data" ON contacts
--     FOR ALL
--         USING (company_id IN (
--             SELECT
--                 cu.company_id
--             FROM
--                 company_users cu
--                 JOIN users u ON u.id = cu.user_id
--             WHERE
--                 u.uuid = auth.uid()));
-- CREATE POLICY "Users can access their company's addresses" ON addresses
--     FOR ALL
--         USING (company_id IN (
--             SELECT
--                 cu.company_id
--             FROM
--                 company_users cu
--                 JOIN users u ON u.id = cu.user_id
--             WHERE
--                 u.uuid = auth.uid()));
-- CREATE POLICY "Users can access their company's items" ON items
--     FOR ALL
--         USING (company_id IN (
--             SELECT
--                 cu.company_id
--             FROM
--                 company_users cu
--                 JOIN users u ON u.id = cu.user_id
--             WHERE
--                 u.uuid = auth.uid()));
-- CREATE POLICY "Users can access their company's orders" ON orders
--     FOR ALL
--         USING (company_id IN (
--             SELECT
--                 cu.company_id
--             FROM
--                 company_users cu
--                 JOIN users u ON u.id = cu.user_id
--             WHERE
--                 u.uuid = auth.uid()));
-- CREATE POLICY "Users can access their companies" ON companies
--     FOR ALL
--         USING (id IN (
--             SELECT
--                 cu.company_id
--             FROM
--                 company_users cu
--                 JOIN users u ON u.id = cu.user_id
--             WHERE
--                 u.uuid = auth.uid()));
