ALTER TABLE "public"."amazon_reports"
    ALTER COLUMN "region" DROP NOT NULL,
    ALTER COLUMN "country" DROP NOT NULL,
    ALTER COLUMN "created_at" DROP NOT NULL,
    ALTER COLUMN "settlement_id" DROP NOT NULL,
    ALTER COLUMN "currency" DROP NOT NULL,
    ALTER COLUMN "marketplace_name" DROP NOT NULL,
    ALTER COLUMN "settlement_start_date" DROP NOT NULL,
    ALTER COLUMN "settlement_end_date" DROP NOT NULL,
    ALTER COLUMN "deposit_date" DROP NOT NULL,
    ALTER COLUMN "net_proceeds" DROP NOT NULL,
    ALTER COLUMN "beginning_balance" DROP NOT NULL,
    ALTER COLUMN "account_reserve_level" DROP NOT NULL,
    ALTER COLUMN "sales_total" DROP NOT NULL,
    ALTER COLUMN "sales_product_charges" DROP NOT NULL,
    ALTER COLUMN "sales_tax" DROP NOT NULL,
    ALTER COLUMN "sales_shipping" DROP NOT NULL,
    ALTER COLUMN "sales_inventory_reimbursements" DROP NOT NULL,
    ALTER COLUMN "sales_other" DROP NOT NULL,
    ALTER COLUMN "refunds_total" DROP NOT NULL,
    ALTER COLUMN "refunds_refunded_sales" DROP NOT NULL,
    ALTER COLUMN "refunds_refunded_expenses" DROP NOT NULL,
    ALTER COLUMN "expenses_total" DROP NOT NULL,
    ALTER COLUMN "expenses_fba_fees" DROP NOT NULL,
    ALTER COLUMN "expenses_amazon_fees" DROP NOT NULL,
    ALTER COLUMN "expenses_promo_rebates" DROP NOT NULL,
    ALTER COLUMN "expenses_cost_of_advertising" DROP NOT NULL;

