CREATE TYPE item_type AS ENUM(
    'product',
    'part'
);

CREATE TYPE order_type AS ENUM(
    'purchase',
    'sale',
    'shipment',
    'stocktake'
);

CREATE TABLE "public"."warehouses"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "name" text
);

CREATE TABLE "public"."items"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "price" numeric(10, 2) NOT NULL,
    "type" item_type NOT NULL
);

CREATE TABLE "public"."item_components"(
    "parent_item_id" bigint NOT NULL,
    "component_item_id" bigint NOT NULL,
    "quantity" numeric(10, 4) NOT NULL,
    PRIMARY KEY (parent_item_id, component_item_id),
    FOREIGN KEY (parent_item_id) REFERENCES items(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (component_item_id) REFERENCES items(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "public"."item_changes"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item_id" bigint NOT NULL REFERENCES items(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "quantity_change" integer NOT NULL,
    "warehouse_id" bigint REFERENCES warehouses(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX idx_item_changes ON public.item_changes(item_id, warehouse_id);

CREATE TABLE "public"."orders"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" order_type NOT NULL,
    "order_date" timestamp with time zone DEFAULT now() NOT NULL,
    "carriage" numeric(10, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE "public"."order_item_changes"(
    "order_id" bigint NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "item_change_id" bigint NOT NULL REFERENCES item_changes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "price" numeric(10, 2),
    "tax" numeric(10, 2),
    PRIMARY KEY (order_id, item_change_id)
);

CREATE INDEX idx_orders_type_date ON public.orders(type, order_date);

CREATE TABLE "public"."stocktakes"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_id" bigint NOT NULL REFERENCES warehouses(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "public"."stocktake_item_changes"(
    "stocktake_id" bigint NOT NULL REFERENCES stocktakes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "item_change_id" bigint NOT NULL REFERENCES item_changes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (stocktake_id, item_change_id)
);

CREATE INDEX idx_stocktakes_warehouse_timestamp ON public.stocktakes(warehouse_id, timestamp);

-- Grant permissions for all tables
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;

-- Individual grants for each table and role
DO $$
DECLARE
    tables text[] := ARRAY['warehouses', 'items', 'item_components', 'item_changes', 'orders', 'order_item_changes', 'stocktakes', 'stocktake_item_changes'];
    roles text[] := ARRAY['anon', 'authenticated', 'service_role'];
    t text;
    r text;
BEGIN
    FOREACH t IN ARRAY tables LOOP
        FOREACH r IN ARRAY roles LOOP
            EXECUTE format('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."%I" TO "%I"', t, r);
        END LOOP;
    END LOOP;
END
$$;

