export const data = [
    {
        order_id: 1184,
        address_id: 2,
        address_name: "Amazon Headquarters",
        transaction_date: "2025-04-11T20:53:52.548+00:00",
        order_date: "2025-04-11T20:53:52.548+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon.com, Inc.",
        items: [
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -23,
                quantity: 88,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 23,
                quantity: 122,
                address_id: 35,
            },
            {
                id: 59,
                name: "Hello Fresh - Large Left (23)",
                type: "package",
                change: 1,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 42,
                name: "Large Right Bag (50)",
                type: "package",
                change: 1,
                quantity: 6,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 50,
                quantity: 150,
                address_id: 35,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -50,
                quantity: 40,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 122,
            "9": 40,
            "42": 6,
            "59": 1,
        },
        items_changed: 4,
        net_change: 2,
    },
    {
        order_id: 1183,
        address_id: 2,
        address_name: "Amazon UK Services Ltd.",
        transaction_date: "2025-04-09T23:00:00+00:00",
        order_date: "2025-04-09T23:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon UK",
        items: [
            {
                id: 55,
                name: "Large Mixed (25 + 25)",
                type: "package",
                change: 1,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -25,
                quantity: 90,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 25,
                quantity: 75,
                address_id: 28,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -25,
                quantity: 111,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 25,
                quantity: 75,
                address_id: 28,
            },
        ],
        item_quantities: {
            "8": 111,
            "9": 75,
            "55": 1,
        },
        items_changed: 3,
        net_change: 1,
    },
    {
        order_id: 1181,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2025-04-03T14:43:52.259+00:00",
        order_date: "2025-04-03T14:43:52.259+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "Pedorthics In Motion",
        items: [
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -24,
                quantity: 64,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -18,
                quantity: 153,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -54,
                quantity: 136,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -42,
                quantity: 115,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 136,
            "9": 115,
            "10": 64,
            "11": 153,
        },
        items_changed: 4,
        net_change: -138,
    },
    {
        order_id: 1179,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2025-03-20T23:23:22.416+00:00",
        order_date: "2025-03-20T23:23:22.416+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 221,
                quantity: 190,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 0,
                quantity: 1675,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 180,
                quantity: 157,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 26,
                name: "Trauma Splint - Right Small",
                type: "product",
                change: 0,
                quantity: 45,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 0,
                quantity: 1100,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 0,
                quantity: 3000,
                address_id: 2,
            },
            {
                id: 27,
                name: "Trauma Splint - Left Small",
                type: "product",
                change: 0,
                quantity: 45,
                address_id: 2,
            },
            {
                id: 25,
                name: "Trauma Splint - Left Large",
                type: "product",
                change: 0,
                quantity: 95,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 43,
                name: "Night Splint - Small Left (Bag)",
                type: "product",
                change: -3,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 80,
                quantity: 88,
                address_id: 2,
            },
            {
                id: 21,
                name: "Trauma Splint - Right Large",
                type: "product",
                change: 0,
                quantity: 95,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 74,
                quantity: 171,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 0,
                quantity: 1875,
                address_id: 2,
            },
            {
                id: 46,
                name: "Night Splint - Small Right (Bag)",
                type: "product",
                change: -1,
                quantity: 0,
                address_id: 2,
            },
        ],
        item_quantities: {
            "3": 900,
            "7": 3000,
            "8": 190,
            "9": 157,
            "10": 88,
            "11": 171,
            "21": 95,
            "25": 95,
            "26": 45,
            "27": 45,
            "28": 900,
            "29": 1675,
            "30": 1100,
            "31": 1875,
            "43": 0,
            "46": 0,
        },
        items_changed: 6,
        net_change: 551,
    },
    {
        order_id: 1175,
        address_id: 2,
        address_name: "Amazon UK Services Ltd.",
        transaction_date: "2025-03-17T00:00:00+00:00",
        order_date: "2025-03-17T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon UK",
        items: [
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: -40,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: 40,
                quantity: 60,
                address_id: 28,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: 40,
                quantity: 60,
                address_id: 28,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: -40,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 35,
                name: "Large Left Box (20)",
                type: "package",
                change: 2,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 37,
                name: "Large Right Box (20)",
                type: "package",
                change: 2,
                quantity: 3,
                address_id: 2,
            },
        ],
        item_quantities: {
            "19": 60,
            "20": 0,
            "35": 3,
            "37": 3,
        },
        items_changed: 4,
        net_change: 4,
    },
    {
        order_id: 1174,
        address_id: 2,
        address_name: "Amazon US",
        transaction_date: "2025-03-17T00:00:00+00:00",
        order_date: "2025-03-17T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon.com, Inc.",
        items: [
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -100,
                quantity: -31,
                address_id: 2,
            },
            {
                id: 41,
                name: "Large Left Bag (50)",
                type: "package",
                change: 2,
                quantity: 5,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 39,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 39,
            },
            {
                id: 42,
                name: "Large Right Bag (50)",
                type: "package",
                change: 2,
                quantity: 5,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -100,
                quantity: -23,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 100,
            "9": -23,
            "41": 5,
            "42": 5,
        },
        items_changed: 4,
        net_change: 4,
    },
    {
        order_id: 1173,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2025-03-10T06:08:38.051+00:00",
        order_date: "2025-03-10T06:08:38.051+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "Brace Yourself ",
        items: [
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -2,
                quantity: 8,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -4,
                quantity: 77,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -2,
                quantity: 97,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -10,
                quantity: 69,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 69,
            "9": 77,
            "10": 8,
            "11": 97,
        },
        items_changed: 4,
        net_change: -18,
    },
    {
        order_id: 1171,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2025-02-09T23:00:00+00:00",
        order_date: "2025-02-09T23:00:00+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "Orthotics Plus",
        items: [
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -3,
                quantity: 99,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -3,
                quantity: 10,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -3,
                quantity: 81,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -3,
                quantity: 79,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 79,
            "9": 81,
            "10": 10,
            "11": 99,
        },
        items_changed: 4,
        net_change: -12,
    },
    {
        order_id: 1170,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2025-01-02T12:33:46.428+00:00",
        order_date: "2025-01-02T12:33:46.428+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "Club Warehouse Australia",
        items: [
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -6,
                quantity: 84,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -6,
                quantity: 82,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -12,
                quantity: 13,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -12,
                quantity: 102,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 82,
            "9": 84,
            "10": 13,
            "11": 102,
        },
        items_changed: 4,
        net_change: -36,
    },
    {
        order_id: 1167,
        address_id: 2,
        address_name: "Amazon Headquarters",
        transaction_date: "2024-12-23T00:00:00+00:00",
        order_date: "2024-12-23T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon.com, Inc.",
        items: [
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 35,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 35,
            },
            {
                id: 34,
                name: "Small Right Box (25)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -100,
                quantity: 138,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -100,
                quantity: 140,
                address_id: 2,
            },
            {
                id: 42,
                name: "Large Right Bag (50)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -50,
                quantity: 139,
                address_id: 2,
            },
            {
                id: 33,
                name: "Small Left Box (25)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 35,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 35,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -50,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 41,
                name: "Large Left Bag (50)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 100,
            "9": 140,
            "10": 50,
            "11": 139,
            "33": 2,
            "34": 2,
            "41": 2,
            "42": 2,
        },
        items_changed: 8,
        net_change: 8,
    },
    {
        order_id: 1168,
        address_id: 2,
        address_name: "Amazon UK Services Ltd.",
        transaction_date: "2024-12-23T00:00:00+00:00",
        order_date: "2024-12-23T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon UK",
        items: [
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 28,
            },
            {
                id: 33,
                name: "Small Left Box (25)",
                type: "package",
                change: 1,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -25,
                quantity: 25,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -25,
                quantity: 114,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 25,
                quantity: 29,
                address_id: 28,
            },
            {
                id: 41,
                name: "Large Left Bag (50)",
                type: "package",
                change: 1,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 34,
                name: "Small Right Box (25)",
                type: "package",
                change: 1,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 42,
                name: "Large Right Bag (50)",
                type: "package",
                change: 1,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -50,
                quantity: 90,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -50,
                quantity: 88,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 28,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 25,
                quantity: 50,
                address_id: 28,
            },
        ],
        item_quantities: {
            "8": 88,
            "9": 50,
            "10": 50,
            "11": 29,
            "33": 3,
            "34": 3,
            "41": 3,
            "42": 3,
        },
        items_changed: 8,
        net_change: 4,
    },
    {
        order_id: 1166,
        address_id: 2,
        address_name: "MPD",
        transaction_date: "2024-12-23T00:00:00+00:00",
        order_date: "2024-12-23T00:00:00+00:00",
        order_type: "shipment",
        from_company: "MPD Hook and Loop",
        to_company: "Thetis Medical Ltd",
        items: [
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -100,
                quantity: 300,
                address_id: 3,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 200,
                quantity: 240,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 100,
                quantity: 189,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 200,
                quantity: 238,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -200,
                quantity: 600,
                address_id: 3,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -200,
                quantity: 600,
                address_id: 3,
            },
            {
                id: 42,
                name: "Large Right Bag (50)",
                type: "package",
                change: 4,
                quantity: 4,
                address_id: 3,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -100,
                quantity: 300,
                address_id: 3,
            },
            {
                id: 41,
                name: "Large Left Bag (50)",
                type: "package",
                change: 4,
                quantity: 4,
                address_id: 3,
            },
            {
                id: 34,
                name: "Small Right Box (25)",
                type: "package",
                change: 4,
                quantity: 4,
                address_id: 3,
            },
            {
                id: 33,
                name: "Small Left Box (25)",
                type: "package",
                change: 4,
                quantity: 4,
                address_id: 3,
            },
        ],
        item_quantities: {
            "8": 600,
            "9": 600,
            "10": 300,
            "11": 189,
            "33": 4,
            "34": 4,
            "41": 4,
            "42": 4,
        },
        items_changed: 8,
        net_change: 16,
    },
    {
        order_id: 1163,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-12-09T21:29:30.966+00:00",
        order_date: "2024-12-09T21:29:30.966+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "The Hospital of St John and St Elizabeth",
        items: [
            {
                id: 25,
                name: "Trauma Splint - Left Large",
                type: "product",
                change: -5,
                quantity: 95,
                address_id: 2,
            },
            {
                id: 26,
                name: "Trauma Splint - Right Small",
                type: "product",
                change: -5,
                quantity: 45,
                address_id: 2,
            },
            {
                id: 27,
                name: "Trauma Splint - Left Small",
                type: "product",
                change: -5,
                quantity: 45,
                address_id: 2,
            },
            {
                id: 21,
                name: "Trauma Splint - Right Large",
                type: "product",
                change: -5,
                quantity: 95,
                address_id: 2,
            },
        ],
        item_quantities: {
            "21": 95,
            "25": 95,
            "26": 45,
            "27": 45,
        },
        items_changed: 4,
        net_change: -20,
    },
    {
        order_id: 1161,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-12-09T20:35:11.075+00:00",
        order_date: "2024-12-09T20:35:11.075+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "The London Foot & Ankle Centre Limited",
        items: [
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: -2,
                quantity: 40,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -4,
                quantity: 38,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 38,
            "19": 40,
        },
        items_changed: 2,
        net_change: -6,
    },
    {
        order_id: 1138,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-11-19T22:49:55.247+00:00",
        order_date: "2024-11-19T22:49:55.247+00:00",
        order_type: "sale",
        from_company: "Thetis Medical Ltd",
        to_company: "Club Warehouse Australia",
        items: [
            {
                id: 43,
                name: "Night Splint - Small Left (Bag)",
                type: "product",
                change: -2,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -4,
                quantity: 40,
                address_id: 2,
            },
            {
                id: 46,
                name: "Night Splint - Small Right (Bag)",
                type: "product",
                change: -3,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: -5,
                quantity: 42,
                address_id: 2,
            },
        ],
        item_quantities: {
            "8": 42,
            "9": 40,
            "43": 3,
            "46": 1,
        },
        items_changed: 4,
        net_change: -14,
    },
    {
        order_id: 1137,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-11-18T20:21:06.344+00:00",
        order_date: "2024-11-18T20:21:06.344+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 21,
                name: "Trauma Splint - Right Large",
                type: "product",
                change: 0,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 8,
                name: "Night Splint - Large Left (Bag)",
                type: "product",
                change: 47,
                quantity: 47,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 11,
                quantity: 89,
                address_id: 2,
            },
            {
                id: 25,
                name: "Trauma Splint - Left Large",
                type: "product",
                change: 0,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 0,
                quantity: 3000,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 0,
                quantity: 1675,
                address_id: 2,
            },
            {
                id: 26,
                name: "Trauma Splint - Right Small",
                type: "product",
                change: 0,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: -45,
                quantity: 44,
                address_id: 2,
            },
            {
                id: 46,
                name: "Night Splint - Small Right (Bag)",
                type: "product",
                change: 4,
                quantity: 4,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 0,
                quantity: 1875,
                address_id: 2,
            },
            {
                id: 27,
                name: "Trauma Splint - Left Small",
                type: "product",
                change: 0,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 0,
                quantity: 1100,
                address_id: 2,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: 20,
                quantity: 40,
                address_id: 2,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: -36,
                quantity: 42,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -6,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 43,
                name: "Night Splint - Small Left (Bag)",
                type: "product",
                change: 5,
                quantity: 5,
                address_id: 2,
            },
        ],
        item_quantities: {
            "3": 900,
            "7": 3000,
            "8": 47,
            "9": 44,
            "10": 0,
            "11": 89,
            "19": 42,
            "20": 40,
            "21": 100,
            "25": 100,
            "26": 50,
            "27": 50,
            "28": 900,
            "29": 1675,
            "30": 1100,
            "31": 1875,
            "43": 5,
            "46": 4,
        },
        items_changed: 8,
        net_change: 0,
    },
    {
        order_id: 1135,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-11-18T19:55:19.275+00:00",
        order_date: "2024-11-18T19:55:19.275+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 0,
                quantity: 1675,
                address_id: 2,
            },
            {
                id: 1,
                name: "Instruction Leaflet",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 2,
                name: "Ziplock Bag (Large)",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 0,
                quantity: 3000,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 0,
                quantity: 89,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 0,
                quantity: 6,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 0,
                quantity: 78,
                address_id: 2,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: 0,
                quantity: 78,
                address_id: 2,
            },
            {
                id: 53,
                name: "Mixed Small (25 Left 4 Right)",
                type: "package",
                change: 0,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: 40,
                quantity: 20,
                address_id: 2,
            },
            {
                id: 21,
                name: "Trauma Splint - Right Large",
                type: "product",
                change: 0,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 52,
                name: "Shells (125 x Small Left)",
                type: "package",
                change: 0,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 25,
                name: "Trauma Splint - Left Large",
                type: "product",
                change: 0,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 51,
                name: "Shells (125 x Small Right)",
                type: "package",
                change: 0,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 26,
                name: "Trauma Splint - Right Small",
                type: "product",
                change: 0,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 50,
                name: "Shells (150 x Large Right)",
                type: "package",
                change: 0,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 27,
                name: "Trauma Splint - Left Small",
                type: "product",
                change: 0,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 49,
                name: "Shells (150 x Large Left)",
                type: "package",
                change: 0,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 0,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 48,
                name: "Webbing Roll (100m)",
                type: "package",
                change: 0,
                quantity: 6,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 0,
                quantity: 1100,
                address_id: 2,
            },
            {
                id: 47,
                name: "Elastic Box (300m)",
                type: "package",
                change: 0,
                quantity: 4,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 0,
                quantity: 1875,
                address_id: 2,
            },
        ],
        item_quantities: {
            "1": 0,
            "2": 0,
            "3": 900,
            "7": 3000,
            "9": 89,
            "10": 6,
            "11": 78,
            "19": 78,
            "20": 20,
            "21": 100,
            "25": 100,
            "26": 50,
            "27": 50,
            "28": 900,
            "29": 1675,
            "30": 1100,
            "31": 1875,
            "47": 4,
            "48": 6,
            "49": 3,
            "50": 3,
            "51": 2,
            "52": 2,
            "53": 1,
        },
        items_changed: 1,
        net_change: 40,
    },
    {
        order_id: 1129,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-11-14T00:00:00+00:00",
        order_date: "2024-11-14T00:00:00+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 4200,
                quantity: 3000,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 1350,
                quantity: 1100,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 2125,
                quantity: 1675,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 1500,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 1350,
                quantity: 900,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 2125,
                quantity: 1875,
                address_id: 2,
            },
            {
                id: 2,
                name: "Ziplock Bag (Large)",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
        ],
        item_quantities: {
            "2": 0,
            "3": 900,
            "7": 3000,
            "28": 900,
            "29": 1675,
            "30": 1100,
            "31": 1875,
        },
        items_changed: 6,
        net_change: 12650,
    },
    {
        order_id: 1136,
        address_id: 2,
        address_name: "Amazon UK Services Ltd.",
        transaction_date: "2024-11-07T00:00:00+00:00",
        order_date: "2024-11-07T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon UK",
        items: [
            {
                id: 35,
                name: "Large Left Box (20)",
                type: "package",
                change: 1,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: -20,
                quantity: -20,
                address_id: 2,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: 20,
                quantity: 20,
                address_id: 28,
            },
            {
                id: 37,
                name: "Large Right Box (20)",
                type: "package",
                change: 1,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 20,
                name: "Night Splint - Large Right (Box)",
                type: "product",
                change: 20,
                quantity: 20,
                address_id: 28,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: -20,
                quantity: 78,
                address_id: 2,
            },
        ],
        item_quantities: {
            "19": 78,
            "20": 20,
            "35": 1,
            "37": 1,
        },
        items_changed: 4,
        net_change: 2,
    },
    {
        order_id: 1134,
        address_id: 2,
        address_name: "Amazon UK Services Ltd.",
        transaction_date: "2024-11-07T00:00:00+00:00",
        order_date: "2024-11-07T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "Amazon UK",
        items: [
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: -25,
                quantity: 6,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 4,
                quantity: 4,
                address_id: 28,
            },
            {
                id: 53,
                name: "Mixed Small (25 Left 4 Right)",
                type: "package",
                change: 1,
                quantity: 1,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: -4,
                quantity: 78,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 25,
                quantity: 25,
                address_id: 28,
            },
        ],
        item_quantities: {
            "10": 25,
            "11": 78,
            "53": 1,
        },
        items_changed: 3,
        net_change: 1,
    },
    {
        order_id: 1133,
        address_id: 2,
        address_name: "MPD",
        transaction_date: "2024-10-28T00:00:00+00:00",
        order_date: "2024-10-28T00:00:00+00:00",
        order_type: "shipment",
        from_company: "Thetis Medical Ltd",
        to_company: "MPD Hook and Loop",
        items: [
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: -250,
                quantity: -250,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: -1200,
                quantity: -1200,
                address_id: 2,
            },
            {
                id: 47,
                name: "Elastic Box (300m)",
                type: "package",
                change: 4,
                quantity: 4,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: -450,
                quantity: -450,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 450,
                quantity: 292,
                address_id: 3,
            },
            {
                id: 52,
                name: "Shells (125 x Small Left)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: -250,
                quantity: -250,
                address_id: 2,
            },
            {
                id: 48,
                name: "Webbing Roll (100m)",
                type: "package",
                change: 6,
                quantity: 6,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 250,
                quantity: 159,
                address_id: 3,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: -450,
                quantity: -450,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: -600,
                quantity: -600,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 450,
                quantity: 280,
                address_id: 3,
            },
            {
                id: 49,
                name: "Shells (150 x Large Left)",
                type: "package",
                change: 3,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 600,
                quantity: 453,
                address_id: 3,
            },
            {
                id: 50,
                name: "Shells (150 x Large Right)",
                type: "package",
                change: 3,
                quantity: 3,
                address_id: 2,
            },
            {
                id: 51,
                name: "Shells (125 x Small Right)",
                type: "package",
                change: 2,
                quantity: 2,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 1200,
                quantity: 750,
                address_id: 3,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 250,
                quantity: 160,
                address_id: 3,
            },
        ],
        item_quantities: {
            "3": 453,
            "7": 750,
            "28": 280,
            "29": -450,
            "30": 159,
            "31": 160,
            "47": 4,
            "48": 6,
            "49": 3,
            "50": 3,
            "51": 2,
            "52": 2,
        },
        items_changed: 12,
        net_change: 20,
    },
    {
        order_id: 1130,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-10-13T23:00:00+00:00",
        order_date: "2024-10-13T23:00:00+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 31,
                quantity: 31,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 82,
                quantity: 82,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: 98,
                quantity: 98,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 89,
                quantity: 89,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
        ],
        item_quantities: {
            "3": 0,
            "7": 0,
            "9": 89,
            "10": 31,
            "11": 82,
            "19": 98,
            "28": 0,
            "29": 0,
            "30": 0,
            "31": 0,
        },
        items_changed: 4,
        net_change: 300,
    },
    {
        order_id: 1131,
        address_id: 2,
        address_name: "Park House",
        transaction_date: "2024-10-13T23:00:00+00:00",
        order_date: "2024-10-13T23:00:00+00:00",
        order_type: "stocktake",
        from_company: null,
        to_company: null,
        items: [
            {
                id: 19,
                name: "Night Splint - Large Left (Box)",
                type: "product",
                change: 0,
                quantity: 98,
                address_id: 2,
            },
            {
                id: 11,
                name: "Night Splint - Small Right (Box)",
                type: "product",
                change: 0,
                quantity: 82,
                address_id: 2,
            },
            {
                id: 1,
                name: "Instruction Leaflet",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 2,
                name: "Ziplock Bag (Large)",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 3,
                name: "Webbing",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 7,
                name: "Elastic",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 31,
                name: "Shell - Left Small",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 30,
                name: "Shell - Right Small",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 29,
                name: "Shell - Left Large",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 9,
                name: "Night Splint - Large Right (Bag)",
                type: "product",
                change: 0,
                quantity: 89,
                address_id: 2,
            },
            {
                id: 28,
                name: "Shell - Right Large",
                type: "part",
                change: 0,
                quantity: 0,
                address_id: 2,
            },
            {
                id: 27,
                name: "Trauma Splint - Left Small",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 26,
                name: "Trauma Splint - Right Small",
                type: "product",
                change: 50,
                quantity: 50,
                address_id: 2,
            },
            {
                id: 25,
                name: "Trauma Splint - Left Large",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 2,
            },
            {
                id: 10,
                name: "Night Splint - Small Left (Box)",
                type: "product",
                change: 0,
                quantity: 31,
                address_id: 2,
            },
            {
                id: 21,
                name: "Trauma Splint - Right Large",
                type: "product",
                change: 100,
                quantity: 100,
                address_id: 2,
            },
        ],
        item_quantities: {
            "1": 0,
            "2": 0,
            "3": 0,
            "7": 0,
            "9": 89,
            "10": 31,
            "11": 82,
            "19": 98,
            "21": 100,
            "25": 100,
            "26": 50,
            "27": 50,
            "28": 0,
            "29": 0,
            "30": 0,
            "31": 0,
        },
        items_changed: 4,
        net_change: 300,
    },
];
